# Generated by Django 5.0.3 on 2024-04-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rest',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
