# Generated by Django 4.1 on 2024-04-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0004_rename_amount_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_from',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders_from', to='trading_app.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders_to', to='trading_app.wallet'),
            preserve_default=False,
        ),
    ]
