# Generated by Django 4.1 on 2024-04-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_remove_order_user_order_wallet_from_order_wallet_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operation',
        ),
        migrations.AlterField(
            model_name='order',
            name='rest',
            field=models.IntegerField(default=models.F('amount')),
        ),
    ]
