# Generated by Django 4.1 on 2024-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0007_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rest',
            field=models.IntegerField(),
        ),
    ]
