# Generated by Django 4.1 on 2024-04-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_order_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
