# Generated by Django 4.1 on 2024-04-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0012_order_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-id']},
        ),
    ]
